# Generated by Django 4.1.1 on 2022-11-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yoga',
            old_name='problem1',
            new_name='problem',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='problem2',
        ),
        migrations.RemoveField(
            model_name='yoga',
            name='problem2',
        ),
    ]
