# Generated by Django 4.1.1 on 2022-11-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0002_rename_problem1_yoga_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='picture',
            field=models.ImageField(upload_to='static'),
        ),
    ]
